[tool.poetry]
name = "data-set-credit-score"
version = "0.1.0"
description = ""
authors = [
  "kenneth vincentius <kennethv1706@idk.com>",
  "wid <wid@widnyana.web.id>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.136.0"
numpy = "^2.4.0"
pandas = "^2.2.1"
scikit-learn = "^1.8.0"
scipy = "^1.15.0"
uvicorn = "^0.48.0"


[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.4.0"
jupyter-server = "^2.16.0"
notebook = "^7.4.0"
nbconvert = "^7.16.6"
streamlit = "^1.45.0"
seaborn = "^0.13.2"
matplotlib = "^3.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
